/* assessment SQL */ 
CREATE DATABASE TRY;
USE TRY;

CREATE TABLE EMPLOYEES
( 
 EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
 E_NAME VARCHAR(100),
 POSITION VARCHAR(100),
 SALARY DECIMAL(10,2),
 HIRE_DATE DATE 
 );
 
 CREATE TABLE EMPLOYEE_AUDIT
 ( 
  AUDIT_ID INT AUTO_INCREMENT PRIMARY KEY,
  EMPLOYEE_ID INT,
  NAME VARCHAR(100),
  POSITION VARCHAR(100),
  SALARY DECIMAL(10,2),
  HIRE_DATE DATE,
  ACTION_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  ACTION TEXT (100)
  );
  
  INSERT INTO employees (E_NAME, position, salary, hire_date) VALUES 
  ('John Doe','Software Engineer', 80000.00, '2022-01-15'),
('Jane Smith', 'Project Manager', 90000.00, '2021-05-22'),
('Alice Johnson', 'UX Designer', 75000.00, '2023-03-01'); 


DELIMITER //
CREATE TRIGGER EMPLO_AUDIT AFTER INSERT ON EMPLOYEES FOR EACH ROW 
BEGIN 
   INSERT INTO EMPLOYEE_AUDIT (EMPLOYEE_ID,SALARY,ACTION,ACTION_DATE) VALUES (NEW.EMPLOYEE_ID,NEW.SALARY, "WELCOME",NOW());
END // 
DELIMITER ;

DELIMITER //
CREATE PROCEDURE ADDEMPLOYEE(IN P_EMPLOYEE_ID INT,
							 IN P_E_NAME VARCHAR(100),
                             IN P_POSITION VARCHAR(100),
                             IN P_HIRE_DATE DATE )
BEGIN 
      INSERT INTO EMPLOYEES ( EMPLOYEE_ID,E_NAME,POSITION,HIRE_DATE) VALUES ( P_EMPLOYEE_ID,P_E_NAME,P_POSITION,P_HIRE_DATE);
END //
DELIMITER ;


DELIMITER //
CREATE PROCEDURE ADD_EMPLO_AUDIT (IN P_EMPLOYEE_ID INT,
                                  IN P_E_NAME VARCHAR(100),
                                  IN P_POSITION VARCHAR(100)) 
BEGIN 
   INSERT INTO EMPLOYEE_AUDIT ( EMPLOYEE_ID,ACTION_DATE,ACTION) VALUES ( P_EMPLOYEE_ID, NOW(), "WELCOME");
END //
DELIMITER ; 



  
 